jobs:
  build:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
      - name: Test with SBT
        run: sbt --batch test
name: test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
